### ISSUE TITLE
Livox Avia support

### ISSUE THREAD

**Issue by w4rlock999** [ryan-brazeal-ufl/OpenMMS#1]
I am trying to make openMMS compatible with livox avia sensor. The thing is I think the first problem that would arise it within the georeferencing code, particulary on azimuth calculation if I am not mistaken bcs it is different from sensor to another? Now I am wondering where could I find the calculation from the pcap to pointcloud xyz of avia or just explain or hint how you manage to do the calculation on mid40 and horizon? I am trying to find on their datasheet but I don't think I manage to find the calculation guide from them.

**Comment by ryan-brazeal-ufl** [comment]
![image](https://user-images.githubusercontent.com/45769456/111916134-1bdd6900-8a3f-11eb-889d-53f3274964ba.png)
It appears that the Avia uses the same reference frame definition for its cartesian and spherical coordinates as the Mid-40 and Horizon sensors, so the georeferencing code that's used for the Mid-40 sensor will still be correct. Perhaps I am misunderstanding your issue? Please let me know.

**Comment by w4rlock999** [comment]
I think I am the one who got your code wrong lol. So my only experience on lidar device before this is VLP 16 and I was using ROS so cmiiw. In the case of VLP as far as i know the data packet of points are not in terms of cartesian but instead just distance with ring/time information if I am not mistaken, then we have to calculate the cartesian our self. 

Now I am wondering how livox packet data (PCAP) structure is. I am trying to make sense and somehow parse the pcap from livox to better understand your code but only find lvx data documentation on their website. Are they the same thing or what?

**Comment by ryan-brazeal-ufl** [comment]
No, PCAP data structure is not the same as LVX. The PCAP format includes a Global Header at the start of the file and then each packet has a header followed by the packet data (i.e., binary data) as specified with the Livox SDK documentation.

See [here](https://wiki.wireshark.org/Development/LibpcapFileFormat#:~:text=The%20libpcap%20file%20format%20is,generate%20pcapng%20files%20by%20default.) for PCAP header info.
See [here](https://github.com/Livox-SDK/Livox-SDK/wiki/Livox-SDK-Communication-Protocol) for Livox packet info.
