### ISSUE TITLE
about coordinate system transformation

### ISSUE THREAD

**Issue by lijieamd** [ryan-brazeal-ufl/OpenMMS#2]
curv2cart() method in georeference is for lat,lon,alt coordinate to ECEF coordinate
but this alt is height above mean sea level from $GPGGA's 9th field
it supposed to be the height above the ellipsoid?

**Comment by ryan-brazeal-ufl** [comment]
Hello,

Thanks for the question. You are correct in that the curvilinear (geodetic) coordinates should be latitude, longitude, and ellipsoidal height when converting to their ECEF Cartesian coordinate representation using the curv2cart() function. You are also correct in that the NMEA GGA message includes the orthometric height (elevation) within field 9. For correctness, the elevation should be converted to ellipsoidal height by adding the geoid separation value found in field 11. 

The logic behind using the **NMEA GGA message is** that it is **only used when storing the lower accuracy, real-time trajectory information** from the APX-18 GNSS-INS sensor during data collection within the .TRAJ file. The .TRAJ file is converted using the `openmms_traj_convert.py` application to produce an ASCII trajectory file that is in the same format as the high-accuracy post-processed trajectory exported from POSPac. Using the .TRAJ file allows for a field-based Quality Assurance (QA) check to be performed immediately after data collection, by producing a lower accuracy georeferenced point cloud and manually viewing it to ensure proper ROI coverage, strip overlap, point density, etc. _**This QA check can be performed using lower accuracy elevations or ellipsoidal heights.**_ But again, you are correct in that ellipsoidal heights should technically be used.

Line 119 in the `openmms_traj_convert.py` application should be changed to:
`returnValues.append(float(position[9]) + float(position[11]))` in order for ellipsoidal heights to be used.

To be thorough, the high-accuracy post-processed trajectory that is exported from POSPac does properly include ellipsoidal heights as well as the corresponding geoid separation values (depending on what Geoid model is selected), and is unaffected by this GGA message issue.

Hopefully this explanation helps your understanding of the thinking behind the process, but thank you for your attention to detail and bring this subject to my attention!

-Ryan

**Comment by lijieamd** [comment]
Hi ryan,
Thanks for you detailed explanation, i took a look at APX's post-process template file "OpenMMS_Export.xsd" again, the 4'th field is exactly "Ellipsoid height", so is OK for high-accuracy post-processed trajectory

Jay
