### ISSUE TITLE
[3_quick_georef_WGS84_UTM13_livox] error: unrecognised option '-lof' on Ubuntu 18.04

### ISSUE THREAD

**Issue by congphase** [ryan-brazeal-ufl/OpenMMS#3]
Hello all, I'm trying to run this awesome project on Linux, the platform that hasn't been tested.

I copied the trigger files from [mac_bash_files](https://github.com/ryan-brazeal-ufl/OpenMMS/tree/master/post_processing/mac_bash_files) to the flight_data folder. 

Additionally, I had to install las2las for Ubuntu with ` sudo apt install  liblas-bin` (v1.8.1) to be able to run the Python script by the `3_quick_georef_WGS84_UTM13_livox`.

However, it yields an error as:

```
                TEMP FILE quick_pc_6of6_temp.las is being CREATED ...
                TEMP FILE quick_pc_1of6_temp.las is DONE!
                TEMP FILE quick_pc_5of6_temp.las is DONE!
                TEMP FILE quick_pc_4of6_temp.las is DONE!
                TEMP FILE quick_pc_3of6_temp.las is DONE!
                TEMP FILE quick_pc_6of6_temp.las is DONE!
                TEMP FILE quick_pc_2of6_temp.las is DONE!

            Merging Point Cloud ...
error: unrecognised option '-lof'
            Deleting temp files...
            Done in 3.07 seconds

```
I checked the [manual of las2las](https://liblas.org/utilities/las2las.html#las2las), but there's no `-l` option. Removing it to have `-of` helps the execution pass that point. However, it will face the same kind of error with `-meter`, `-merged`, `-epsg` options. 

It looks like the options set up in the Python code literally make sense (merged, meter, ...), which seem not to be formed from separate options (-f, -o, -m, -e, ...).

Please help clarify this.

**Comment by ryan-brazeal-ufl** [comment]
Hello,
The option is -lof (singular) to read input from a list of files.
Ryan

<img width="513" alt="Screen Shot 2021-07-21 at 6 43 40 AM" src="https://user-images.githubusercontent.com/45769456/126490744-b12b8168-da54-4c11-86f8-87c16aa8fbb5.png">
