### ISSUE TITLE
Does it make organized pointclouds?

### ISSUE THREAD

**Issue by FPSychotic** [ryan-brazeal-ufl/OpenMMS#5]
Hi, I'm sorry if my question is very basic, but  I would like to know if the pointcloud resultant are organized or unorganized. ( Mainly to can fuse with photogrammetry or make meshes , as Reality Capture software in example don't work with unorganized pointclouds.

**Comment by ryan-brazeal-ufl** [comment]
The point clouds are unorganized due to the dynamic nature of the sensor platform/vehicle during mapping operations.
