### ISSUE TITLE
OpenMMS_Demo_1.zip on Google Drive is corrupt

### ISSUE THREAD

**Issue by chippey** [ryan-brazeal-ufl/OpenMMS#6]
Hello!  After downloading a couple of times the OpenMMS_Demo_1.zip from your Google drive, I am unable to decompress it - it always errors, so I'm assuming it's corrupt?  This is on both MacOS and Linux.

**Comment by ryan-brazeal-ufl** [comment]
Hey, chippey. The demo1 data has been re-uploaded to Google Drive and the download link within the Tutorial 1 documentation has been updated. Thanks.
